name: 🎵 Update Currently Listening

on:
  schedule:
    - cron: "*/10 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-card:
    runs-on: ubuntu-latest

    steps:

      # ----------------------------------------
      # Checkout repository
      # ----------------------------------------

      - name: Checkout repository
        uses: actions/checkout@v6


      # ----------------------------------------
      # Generate Last.fm card
      # ----------------------------------------

      - name: Generate Last.fm card
        env:
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}

        run: |
          node scripts/generate-lastfm-card.js


      # ----------------------------------------
      # Commit generated SVG
      # ----------------------------------------

      - name: Commit updated card
        uses: stefanzweifel/git-auto-commit-action@v7

        with:
          commit_message: "🎵 Update currently listening"

          file_pattern: assets/currently-listening.svg
